## Création du pipeline de déploiement continu

name: Pipeline-CD
on:
    push:
        branches:
          - main
          - develop
jobs:
    cd:
        runs-on: ubuntu-latest
        continue-on-error: false
        steps:
            - uses: actions/checkout@v2
            - name: Deploy Over SSH
              uses: appleboy/ssh-action@v0.1.7
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: ${{ secrets.SSH_PORT }}
                script: |
                    cd ameliedev/Site-ameliedev.fr
                    git pull
                    cd frontend
                    export NVM_DIR="$HOME/.nvm"
                    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                    nvm install --lts
                    node -v
                    npm -v