## Création du pipeline de déploiement continu

name: Pipeline-CD
on:
    push:
        branches: [ develop ]
jobs:
    cd:
        runs-on: ubuntu-latest
        continue-on-error: false
        steps:
            - uses: actions/checkout@v2
            - name: Deploy Over SSH
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                password: ${{ secrets.PASSWORD }}
                port: ${{ secrets.SSH_PORT }}
                script: ls