## Création du pipeline de déploiement continu

name: Pipeline-CD
on:
    push:
        branches:
          - main
          - develop
jobs:
    cd:
        runs-on: ubuntu-latest
        continue-on-error: false
        steps:
            - uses: actions/checkout@v2
            - name: Deploy Over SSH
              uses: |
                appleboy/ssh-action@v0.1.7
                borales/actions-yarn@v4
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                port: ${{ secrets.SSH_PORT }}
                script: |
                    cd ameliedev/Site-ameliedev.fr
                    git pull
                    composer install --optimize-autoloader
                    yarn --production
                    yarn build
                    php bin/console cache:clear
                    php bin/console cache:warmup
                    APP_ENV=prod
                    APP_DEBUG=0
                    composer dump-env prod
#                    php bin/console doctrine:create:database --if-not-exists
#                    php bin/console doctrine:migrations:migrate --no-interaction
